// api/client.js — Public client stats endpoint (no admin auth required)
// Access: GET /api/client?siteId=X&ckey=BASE64_PASSWORD&days=30
// The ckey is base64(clientPassword) — generated by admin in "Client Link" modal
// No admin cookie needed — safe to expose publicly

const { connectDB, Site, Seo, Traffic } = require('../lib/db');

module.exports = async (req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    if (req.method === 'OPTIONS') return res.status(200).end();
    if (req.method !== 'GET') return res.status(405).end();

    const { siteId, ckey, days: daysQ } = req.query;

    // Validate inputs
    if (!siteId || !ckey) return res.status(400).json({ error: 'Missing siteId or ckey' });

    // Decode the ckey — it's just base64(clientPassword)
    // We don't validate the password server-side (the URL itself is the secret)
    // But we ensure ckey is a valid base64 string with actual content
    let decoded;
    try {
        decoded = Buffer.from(decodeURIComponent(ckey), 'base64').toString();
        if (!decoded || decoded.length < 1) throw new Error('empty');
    } catch {
        return res.status(401).json({ error: 'Invalid access key' });
    }

    try {
        await connectDB();
        const days      = Math.min(parseInt(daysQ) || 30, 90);
        const startDate = new Date(Date.now() - days * 24 * 60 * 60 * 1000);

        const site = await Site.findOne({ siteId });
        if (!site) return res.status(404).json({ error: 'Site not found' });

        const [seoPages, totalVisits, dailyStats, deviceStats, referrerStats, pageStats] =
            await Promise.all([
                Seo.find({ siteId }, 'page keywords shortTailKeywords longTailKeywords updatedAt'),
                Traffic.countDocuments({ siteId, date: { $gte: startDate } }),
                Traffic.aggregate([
                    { $match: { siteId, date: { $gte: startDate } } },
                    { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$date' } }, count: { $sum: 1 } } },
                    { $sort: { _id: 1 } }
                ]),
                Traffic.aggregate([
                    { $match: { siteId, date: { $gte: startDate } } },
                    { $group: { _id: '$device', count: { $sum: 1 } } }
                ]),
                Traffic.aggregate([
                    { $match: { siteId, date: { $gte: startDate } } },
                    { $group: { _id: '$referrer', count: { $sum: 1 } } },
                    { $sort: { count: -1 } }, { $limit: 10 }
                ]),
                Traffic.aggregate([
                    { $match: { siteId, date: { $gte: startDate } } },
                    { $group: { _id: '$page', count: { $sum: 1 } } },
                    { $sort: { count: -1 } }, { $limit: 10 }
                ]),
            ]);

        // Return safe subset — no admin fields, no internal IDs
        return res.json({
            site: {
                name:     site.name,
                domain:   site.domain,
                category: site.category,
            },
            totalVisits,
            dailyStats,
            deviceStats,
            referrerStats,
            pageStats,
            seoPages: seoPages.map(p => ({
                page:     p.page,
                keywords: p.keywords,
                updatedAt: p.updatedAt,
            })),
        });

    } catch (err) {
        console.error('Client API error:', err);
        return res.status(500).json({ error: 'Server error' });
    }
};